// Mock data for demo mode - allows testing without Supabase

export const DEMO_FAMILIES = {
  'family-1': {
    id: 'family-1',
    name: 'Johnson Squadron',
    subscription_status: 'active',
    created_at: new Date().toISOString(),
  },
}

export const DEMO_USERS = {
  // Commander Account
  'commander-1': {
    id: 'commander-1',
    email: 'commander@demo.com',
    full_name: 'Sarah Johnson',
    role: 'commander' as const,
    family_id: 'family-1',
    avatar_url: null,
    agent_code: 'CMD-1001',
    rank_points: 0,
    current_rank: 'RECRUIT',
    date_of_birth: null,
    created_at: new Date().toISOString(),
    last_active: new Date().toISOString(),
  },
  // Agent Account 1 (Kid)
  'agent-1': {
    id: 'agent-1',
    email: null,
    full_name: 'Tommy Johnson',
    role: 'agent' as const,
    family_id: 'family-1',
    avatar_url: null,
    agent_code: 'AGENT-2051',
    rank_points: 245,
    current_rank: 'FIELD AGENT',
    date_of_birth: '2012-05-15',
    created_at: new Date().toISOString(),
    last_active: new Date().toISOString(),
  },
  // Agent Account 2 (Kid)
  'agent-2': {
    id: 'agent-2',
    email: null,
    full_name: 'Emma Johnson',
    role: 'agent' as const,
    family_id: 'family-1',
    avatar_url: null,
    agent_code: 'AGENT-3074',
    rank_points: 125,
    current_rank: 'JUNIOR AGENT',
    date_of_birth: '2015-09-22',
    created_at: new Date().toISOString(),
    last_active: new Date().toISOString(),
  },
}

export const DEMO_MISSIONS = [
  {
    id: 'mission-1',
    family_id: 'family-1',
    title: 'Operation: Clean Room',
    description: 'Make your bed, put away all toys, vacuum the floor, and organize your desk.',
    category: 'room',
    difficulty: 'medium' as const,
    status: 'pending',
    created_by: 'commander-1',
    assigned_to: 'agent-1',
    due_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    recurring: false,
    recurrence_pattern: null,
    rank_points: 25,
    field_bonus: null,
    is_verified: false,
    created_at: new Date().toISOString(),
    completed_at: null,
    verified_at: null,
    assignedAgent: {
      full_name: 'Tommy Johnson',
      avatar_url: null,
    },
  },
  {
    id: 'mission-2',
    family_id: 'family-1',
    title: 'Mission: Take Out Trash',
    description: 'Empty all trash cans in the house and take the bags to the outdoor bin.',
    category: 'cleaning',
    difficulty: 'easy' as const,
    status: 'in_progress',
    created_by: 'commander-1',
    assigned_to: 'agent-2',
    due_date: new Date().toISOString(),
    recurring: true,
    recurrence_pattern: 'weekly_monday',
    rank_points: 10,
    field_bonus: 0.5,
    is_verified: false,
    created_at: new Date().toISOString(),
    completed_at: null,
    verified_at: null,
    assignedAgent: {
      full_name: 'Emma Johnson',
      avatar_url: null,
    },
  },
  {
    id: 'mission-3',
    family_id: 'family-1',
    title: 'Kitchen Duty: Dishes',
    description: 'Load the dishwasher, hand-wash pots and pans, wipe down counters.',
    category: 'dishes',
    difficulty: 'medium' as const,
    status: 'awaiting_verification',
    created_by: 'commander-1',
    assigned_to: 'agent-1',
    due_date: new Date().toISOString(),
    recurring: true,
    recurrence_pattern: 'daily',
    rank_points: 25,
    field_bonus: 1.0,
    is_verified: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    verified_at: null,
    assignedAgent: {
      full_name: 'Tommy Johnson',
      avatar_url: null,
    },
  },
  {
    id: 'mission-4',
    family_id: 'family-1',
    title: 'Homework Protocol',
    description: 'Complete all homework assignments and practice reading for 20 minutes.',
    category: 'homework',
    difficulty: 'hard' as const,
    status: 'completed',
    created_by: 'commander-1',
    assigned_to: 'agent-2',
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    recurring: true,
    recurrence_pattern: 'weekly_weekday',
    rank_points: 50,
    field_bonus: null,
    is_verified: true,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verified_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedAgent: {
      full_name: 'Emma Johnson',
      avatar_url: null,
    },
  },
  {
    id: 'mission-5',
    family_id: 'family-1',
    title: 'Pet Care: Feed Max',
    description: 'Feed the dog, refill water bowl, and take Max for a 15-minute walk.',
    category: 'pets',
    difficulty: 'easy' as const,
    status: 'completed',
    created_by: 'commander-1',
    assigned_to: 'agent-1',
    due_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    recurring: true,
    recurrence_pattern: 'daily',
    rank_points: 10,
    field_bonus: null,
    is_verified: true,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    verified_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedAgent: {
      full_name: 'Tommy Johnson',
      avatar_url: null,
    },
  },
  {
    id: 'mission-6',
    family_id: 'family-1',
    title: 'Outdoor Operations: Mow Lawn',
    description: 'Mow the front and back yard, trim edges, and put away equipment.',
    category: 'outdoor',
    difficulty: 'hard' as const,
    status: 'pending',
    created_by: 'commander-1',
    assigned_to: null, // Unassigned - available to any agent
    due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    recurring: false,
    recurrence_pattern: null,
    rank_points: 50,
    field_bonus: 5.0,
    is_verified: false,
    created_at: new Date().toISOString(),
    completed_at: null,
    verified_at: null,
  },
]

export const DEMO_ACHIEVEMENTS = [
  {
    id: 'achievement-1',
    user_id: 'agent-1',
    badge_type: 'first_mission',
    earned_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    badge_name: 'First Mission',
    badge_icon: '▲',
  },
  {
    id: 'achievement-2',
    user_id: 'agent-1',
    badge_type: 'week_warrior',
    earned_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    badge_name: 'Week Warrior',
    badge_icon: '◆',
  },
  {
    id: 'achievement-3',
    user_id: 'agent-2',
    badge_type: 'first_mission',
    earned_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    badge_name: 'First Mission',
    badge_icon: '▲',
  },
  {
    id: 'achievement-4',
    user_id: 'agent-1',
    badge_type: 'century_club',
    earned_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    badge_name: 'Century Club',
    badge_icon: '■',
  },
]

export const DEMO_REWARDS = [
  {
    id: 'reward-1',
    family_id: 'family-1',
    title: 'Ice Cream Trip',
    cost_in_points: 50,
    created_by: 'commander-1',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'reward-2',
    family_id: 'family-1',
    title: 'Extra Screen Time (30 min)',
    cost_in_points: 30,
    created_by: 'commander-1',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'reward-3',
    family_id: 'family-1',
    title: 'Movie Night Pick',
    cost_in_points: 75,
    created_by: 'commander-1',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'reward-4',
    family_id: 'family-1',
    title: 'New Toy ($20 budget)',
    cost_in_points: 200,
    created_by: 'commander-1',
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const DEMO_ACCOUNTS = [
  {
    email: 'commander@demo.com',
    password: 'demo123',
    userId: 'commander-1',
    role: 'commander',
    name: 'Sarah Johnson (Commander)',
  },
  {
    email: 'agent1@demo.com',
    password: 'demo123',
    userId: 'agent-1',
    role: 'agent',
    name: 'Tommy Johnson (Agent)',
  },
  {
    email: 'agent2@demo.com',
    password: 'demo123',
    userId: 'agent-2',
    role: 'agent',
    name: 'Emma Johnson (Agent)',
  },
]
